### ISSUE TITLE
Allow subscribers to unsubscribe from events

### ISSUE THREAD

**Issue by tpett** [jbgo/chasqui#16]
After looking through the code I'm not sure how unsubscribing queues from a channel will work. I'm guessing at the moment if you removed a given subscription from the code the Chasqui worker would continue pushing work into that Redis list until you manually removed it from the set of subscribers.

**Comment by jbgo** [comment]
Haha, yes! Man, I've been so heads down I forgot to add it in. Will make this a feature request.

**Comment by jbgo** [comment]
added in 7fc9fc1e
